name: Linux Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install build prerequsites
        run: sudo apt-get install -y python3-pip libxkbcommon-dev libcairo2-dev libwayland-dev libxrandr-dev libxi-dev libxcursor-dev libxdamage-dev libxinerama-dev libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev ninja-build
      - name: Install python modules
        run: sudo python3 -m pip install meson==0.57.1
      - name: Clone gtk repo
        run: git clone https://gitlab.gnome.org/GNOME/gtksourceview.git
      - name: Checkout tag
        run: cd gtksourceview && git checkout tags/5.2.0
      - name: Create build dir
        run: mkdir build
      - name: Configure
        run: meson --prefix=/opt/gtk build
      - name: Build gtk
        run: cd build && ninja && ninja install