name: Linux Build

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install build prerequsites
        run: sudo apt-get install -y libgtk-4-dev build-essential
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Cargo build
        run: cargo build --release
      - name: Install AppImageTool
        run: wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage && sudo mv appimagetool-x86_64.AppImage /usr/local/bin/appimagetool && chmod +x /usr/local/bin/appimagetool
      - name: Create AppImage
        run: ./createAppImage.sh
      - uses: actions/upload-artifact@v2
        with:
          name: gtk_min-x86_64.AppImage
          path: gtk_min-x86_64.AppImage
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: gtk_min-x86_64.AppImage