name: Linux Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install build prerequsites
        run: sudo apt-get install -y python3-pip libxkbcommon-dev libcairo2-dev libwayland-dev libxrandr-dev libxi-dev libxcursor-dev libxdamage-dev libxinerama-dev libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev ninja-build
      - name: Install python modules
        run: sudo python3 -m pip install meson==0.57.1
      - uses: actions/cache@v2
        with:
          path: |
            /tmp/gtkbuild
            /opt/gtk
          key: ${{ runner.os }}-${{ hashFiles('gtksourceview/.git/HEAD') }}
      - name: Clone gtk repo
        run: git clone https://gitlab.gnome.org/GNOME/gtksourceview.git
      - name: Checkout tag
        working-directory: gtksourceview
        run: git checkout tags/5.2.0
      - name: Create build dir
        run: mkdir gtkbuild
        working-directory: /tmp
      - name: Configure
        run: meson --prefix=/opt/gtk /tmp/gtkbuild
        working-directory: gtksourceview
      - name: Build gtk
        run: ninja && ninja install
        working-directory: /tmp/gtkbuild
      - name: Cargo build
        run: build.sh