name: MacOS Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-10.15

    steps:
      - name: Install gtk prerequsites
        run: brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/c163ac5c815d26b98d3cee8e01028749be02621f/Formula/gtk4.rb
      - name: Install more prerequsites
        run: brew install gtksourceview5 adwaita-icon-theme openssl@1.1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-bundle
        run: cargo install cargo-bundle
      - uses: actions/checkout@v2
      - name: Build
        run: cargo-bundle bundle --release --format osx
      - name: Generate Bundle
        run: ./createMacOsBundle.sh
      - uses: actions/upload-artifact@v2
        with:
          name: GtkMin
          path: target/release/bundle/osx/gtk_min.dmg
