name: MacOS Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-10.15

    steps:
      - name: install gtk build system
        run: /bin/bash -c "$(curl -fsSL https://gitlab.gnome.org/GNOME/gtk-osx/-/raw/master/gtk-osx-setup.sh)"
      - name: test 1
        run: ~/.new_local/bin/jhbuild shell && alias jhbuild="PATH=.new_local/bin:$PATH jhbuild" && jhbuild bootstrap-gtk-osx && jhbuild build meta-gtk-osx-bootstrap meta-gtk-osx-gtk4